# Generated by Django 5.1.1 on 2024-09-20 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_name', models.CharField(max_length=50)),
                ('dob', models.DateField(verbose_name='date of birth')),
                ('author_id', models.IntegerField(primary_key=True, serialize=False)),
                ('author_bio', models.CharField(max_length=1000)),
                ('author_pic', models.ImageField(unique=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('pub_date', models.DateField(verbose_name='date published')),
                ('t_nail', models.ImageField(unique=True, upload_to='')),
                ('b_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skfansite.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewer', models.CharField(max_length=50)),
                ('review_id', models.IntegerField(primary_key=True, serialize=False)),
                ('review_text', models.CharField(max_length=1000)),
                ('review_title', models.CharField(max_length=30)),
                ('b_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skfansite.book')),
            ],
        ),
    ]
