# Generated by Django 5.1.1 on 2024-09-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skfansite', '0002_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='blurb',
            field=models.CharField(default='Lorem Ipsum', max_length=1000),
        ),
    ]
