# Generated by Django 5.1.1 on 2024-09-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skfansite', '0003_book_blurb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='t_nail',
            field=models.ImageField(blank=True, default='fallback.png', unique=True, upload_to=''),
        ),
    ]
