# Generated by Django 5.1.1 on 2024-09-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skfansite', '0005_alter_author_author_pic_alter_book_t_nail'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
