# Generated by Django 5.1.1 on 2024-09-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skfansite', '0006_book_pages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
